### ISSUE TITLE
Is anyone at Mozilla updating this?

### ISSUE THREAD

**Issue by Gitoffthelawn** [mozilla/release-blog#15]
Is anyone at Mozilla updating this, or has this project ceased?  The data and associated website are woefully outdated.

**Comment by sylvestre** [comment]
Yes, we are using it from time to time. 
Which outdated data are you referring to?

**Comment by Gitoffthelawn** [comment]
LOL.  When I posted, this repo hadn't been updated since 2015.  All the data between Firefox 43 to Firefox 50 is still missing.

**Comment by Gitoffthelawn** [comment]
@sylvestre All the data between Firefox 43 and Firefox 50.1.0 is missing.

**Comment by sylvestre** [comment]
yeah, I didn't get much feedback about these stats. I stopped for a few weeks because I was too busy with release management.
Nobody complained that we stopped... So, I guess this wasn't too interesting at the end :(

**Comment by Gitoffthelawn** [comment]
@sylvestre 
Personally, I found this list very useful in real-time (as releases were made), as well as historically.

**Comment by sylvestre** [comment]
thanks for the feedback
Maybe I could do this work between two releases  (without the list of changeset)

**Comment by Gitoffthelawn** [comment]
@sylvestre Not quite sure what you mean, but it sounds promising. :)
