### ISSUE TITLE
Blog site isn't secure

### ISSUE THREAD

**Issue by BryanQuigley** [mozilla/release-blog#16]
If you go to https://release.mozilla.org/ with Firefox it warns because the cert is wrong.

**Comment by bkerensa** [comment]
This is because the certificate is for github.io not the custom domain name and so there is certificate name mismatch

**Comment by jcristau** [comment]
github pages doesn't support https for custom domains, so I guess fixing this would imply moving release.mozilla.org to some CDN.

**Comment by sylvestre** [comment]
Moved here: https://bugzilla.mozilla.org/show_bug.cgi?id=1357118

**Comment by pascalchevrel** [comment]
Fixed
